"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def all_fibs(n):
    fibs = [1, 2]
    while fibs[-1] <= n:
        fibs.append(fibs[-1] + fibs[-2])
    return fibs


def sum_even_numbers(fib_list):
    return sum(i for i in fib_list if i % 2 == 0)

def problem_2(n=4000000):
    return sum_even_numbers(all_fibs(n))

if __name__ == "__main__":
    print problem_2()
